### ISSUE TITLE
Still the program not working once a quiz found!

### ISSUE THREAD

**Issue by Akandeil** [r00tmebaby/LinkedIn-Downloader#12]
Hi,
Thanks a lot for your great efforts. I just want to report an issue that the program still stop working once a quiz found! and hereunder the log:

Traceback (most recent call last):
  File "loader.py", line 376, in <module>
  File "loader.py", line 356, in downloader
  File "site-packages\selenium\webdriver\remote\webelement.py", line 80, in clic
k
  File "site-packages\selenium\webdriver\remote\webelement.py", line 633, in _ex
ecute
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in exec
ute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in c
heck_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element cl
ick intercepted: Element <button class="vjs-control vjs-button vjs-next-button"
type="button" aria-disabled="false" data-artdeco-is-focused="true" title="Next">
...</button> is not clickable at point (329, 16). Other element would receive th
e click: <ul class="nav-bar__items">...</ul>
  (Session info: chrome=78.0.3904.97)

[2808] Failed to execute script loader

appreciate your support to fix it.

Thanks

**Comment by r00tmebaby** [comment]
Will look at it, in the next few days

**Comment by Akandeil** [comment]
I can see the issue is closed, is it already fixed?
