### ISSUE TITLE
Could not locate element exception

### ISSUE THREAD

**Issue by ahmednagdy** [r00tmebaby/LinkedIn-Downloader#37]
I setup delays to be 5 or more and manually logged in and still got this

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedInDL.py", line 453, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name-content"}
  (Session info: chrome=80.0.3987.106)

**Comment by theobserver** [comment]
I have the same problem.
But the chrome window is opening ok and the selected course is starting to play in it.

**Comment by r00tmebaby** [comment]
Try to increase some of the timings.

**Comment by theobserver** [comment]
I increased all timings to 10 and then to 30 but the problem persists :(
Is there something else i could try?

**Comment by r00tmebaby** [comment]
Hi @theobserver,

Hmm, it's quite strange that worked and recently stopped. I haven't got any idea what the reason behind could be since it worked to give you precise advice. 

If you could create a record video or screenshots what is happening so I can eventually see the issue would be great.

I will do my best to help you out, that's for sure.

Regards

**Comment by theobserver** [comment]
Hi again mate,
thank you for trying to help.
I have uploaded a video you can see what is happening [here](http://35.208.168.38/~topgreek/!Various/2020-02-28.mp4)

I hope the video is good and you can read.
Thank you for trying to help me and excuse my lame english...

Regards.

**Comment by r00tmebaby** [comment]
Hi @theobserver 

I found that Linkedin has changed some of the styles. A temporary fix is applied to the python versions which you can download from here:

https://github.com/r00tmebaby/LinkedIn-Downloader/tree/master/Python%20Source%20Code/Version%200.16.3 

Make sure you have Python and all dependencies installed prior to run it.

**Comment by gpowa** [comment]
Hi,
the Result is same as before:

`Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: F:\downloads\UL\Neuer Ordner\LinkedIn-Downloader-master\Python Source Code\Version 0.16.3\Loader.py

[2m[36m###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    29/02/2020            #
#     @version: GUI 0.16.3                    #
##############################################

[0m
[35m[[36m*[35m][36m Trying to login on LinkedIn[0mException in thread [0mThread-1[0m:
[0mTraceback (most recent call last):
[0m  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
[0m    [0mself.run()[0m
[0m  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
[0m    [0mself._target(*self._args, **self._kwargs)[0m
[0m  File "F:\downloads\UL\Neuer Ordner\LinkedIn-Downloader-master\Python Source Code\Version 0.16.3\Loader.py", line 424, in downloader
[0m    [0mdriver.find_element_by_id("username").clear()[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
[0m    [0mreturn self.find_element(by=By.ID, value=id_)[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
[0m    [0mreturn self.execute(Command.FIND_ELEMENT, {[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
[0m    [0mself.error_handler.check_response(response)[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
[0m    [0mraise exception_class(message, screen, stacktrace)[0m
[0mselenium.common.exceptions[0m.[0mNoSuchElementException[0m: [0mMessage: no such element: Unable to locate element: {"method":"css selector","selector":"[id="username"]"}
  (Session info: chrome=80.0.3987.122)
[0m
[0m`

**Comment by theobserver** [comment]
Hi again @r00tmebaby 
i am a noob and i have no idea how to do it under the python environment but i am not lazy i will try to.
So at this point i cannot confirm the post of @gpowa above

I installed python (easy) i opened python (easy) but when i give the commands :
pip install requests
pip install selenium
pip install colorama
pip install tqdm
pip install pysimplegui
i get a syntax error for each one. Obviously i am a noob i have no idea of the python environment and i am doing something wrong, though i will try to learn what i am supposed to do.

A windows executable version would be great for us noobs. Much obliged for your work and i hope i am not asking too much from you.

Thank you for your time reading this and excuse my lame English.

Regards.

**Comment by gpowa** [comment]
Hello @theobserver ,

here is howto:

- Install Python 3.82 from Website
- Open Elevated CMD
- Got o Dir of Python 3.8 (c:\Program Files\Python3.8)
- execute commands one for one (look if there is a error or satisfied)
- then open python IDLE from Startmenu of windows
- then in IDLE -> File, Open
- select in Version 0.16.3 the File Loader.py
- execute from Menu "Run Run Module (F5)"

Thats it

**Comment by r00tmebaby** [comment]
Hello @gpowa and @theobserver,

@gpowa in your case it seems that the program can not find the login automatically, so please use the manual login variant. Increase the manual login time in settings run the program, navigate to LinkedIn learning login page and login, after the time you have set expire the program will continue from there.

@@theobserver  ok, I will compile an executable for you, just wanted to make sure that the fix is working for all before that's why I left only python version for analysing.

**Comment by gpowa** [comment]
@r00tmebaby 

no changes if i login manualy. See screenshot
![Screenshot](https://user-images.githubusercontent.com/48104889/75627454-858a9b00-5bd0-11ea-808b-77368ce698ad.JPG)

and log is here:

`[0mException in thread [0mThread-1[0m:
[0mTraceback (most recent call last):
[0m  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
[0m    [0mself.run()[0m
[0m  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
[0m    [0mself._target(*self._args, **self._kwargs)[0m
[0m  File "F:\downloads\UL\Neuer Ordner\LinkedIn-Downloader-master\Python Source Code\Version 0.16.3\Loader.py", line 456, in downloader
[0m    [0mdriver.find_element_by_css_selector([0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
[0m    [0mreturn self.find_element(by=By.CSS_SELECTOR, value=css_selector)[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
[0m    [0mreturn self.execute(Command.FIND_ELEMENT, {[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
[0m    [0mself.error_handler.check_response(response)[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
[0m    [0mraise exception_class(message, screen, stacktrace)[0m
[0mselenium.common.exceptions[0m.[0mNoSuchElementException[0m: [0mMessage: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name.course-body__info-tab-name-content.ember-view"}
  (Session info: chrome=80.0.3987.122)
[0m
`

**Comment by r00tmebaby** [comment]
Hi @gpowa 
What I see from the screenshot is that the "Content" tab for which the program is looking for is missing. It may be hidden on the left side of the window under the dropdown menu. Is that a mobile version of the web? What operation system are you using, it seems that the view that you have is much different from the normal one seems like a mobile version of the website.

When you run the program try to maximize the window so eventually, this dropdown menu disappears and the contents tab become visible. You should normally see this window:
<img src='https://i.gyazo.com/8b7440caacc6ead71515f17f66379bcf.jpg'>

I have also noticed that your web is in German, I do not think that they change the styles based on the language but who knows.. that may be another potential issue.

**Comment by gpowa** [comment]
@r00tmebaby 

Hello,
i try this two cases, but no difference. It gives me the same error.
In your screenshot i see the lessons on the right side. In my lesson it is on the left side.
maybe it is in Germany an other Linkedin-Server ? the Url is above screenshot.

> https://www.linkedin.com/learning/conquering-writer-s-block/wrapping-up

> [0m
[2m[36m###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    29/02/2020            #
#     @version: GUI 0.16.3                    #
##############################################

[0mException in thread [0mThread-2[0m:
[0mTraceback (most recent call last):
[0m  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
[0m    [0mself.run()[0m
[0m  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
[0m    [0mself._target(*self._args, **self._kwargs)[0m
[0m  File "F:\downloads\UL\Neuer Ordner\LinkedIn-Downloader-master\Python Source Code\Version 0.16.3\Loader.py", line 456, in downloader
[0m    [0mdriver.find_element_by_css_selector([0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
[0m    [0mreturn self.find_element(by=By.CSS_SELECTOR, value=css_selector)[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
[0m    [0mreturn self.execute(Command.FIND_ELEMENT, {[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
[0m    [0mself.error_handler.check_response(response)[0m
[0m  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
[0m    [0mraise exception_class(message, screen, stacktrace)[0m
[0mselenium.common.exceptions[0m.[0mNoSuchElementException[0m: [0mMessage: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name.course-body__info-tab-name-content.ember-view"}
  (Session info: chrome=80.0.3987.122)
[0m
[0m

![Screenshot5](https://user-images.githubusercontent.com/48104889/75747853-51bd8b80-5d1e-11ea-9942-4f1bad80b88e.JPG)

**Comment by theobserver** [comment]
Hi again,
by following your instructions i managed to load the 5 pip commands but then when i was trying to run it i was getting the error that chrome is not available and should download it.
Also there is not 16.4 ver in the python source code directory. Also the 16.3 dir was a bit empty so i used the 0.16 ver directory which missed the chromedriver.exe.
Anyway it was pretty difficult for me to do since i did not know what to copy in the directory.
You can see what happened [here](http://35.208.168.38/~topgreek/!Various/via python.mp4)

Then i tried to run the executable. The 16.4 ver executable has some problems.
1. The login tab is missing completely.
2.  The exercise files and subs options are missing.
3. It didn't work.

You can see what happened [here](http://35.208.168.38/~topgreek/!Various/Executable .mp4)

Thank you for your time.

Regards,
Nik

**Comment by gpowa** [comment]
@theobserver 

first steps ok then:

- then open python IDLE from Startmenu of windows
- then in IDLE -> File, Open
- select in Version 0.16.3 the File Loader.py
- execute from Menu "Run Run Module (F5)"

![Screenshot6](https://user-images.githubusercontent.com/48104889/75813833-fbd5fb80-5d90-11ea-9565-ffa29f60f306.JPG)
![Screenshot7](https://user-images.githubusercontent.com/48104889/75813834-fc6e9200-5d90-11ea-82da-6cc508b2d546.JPG)
![Screenshot8](https://user-images.githubusercontent.com/48104889/75813836-fc6e9200-5d90-11ea-8677-423184a6982a.JPG)

**Comment by theobserver** [comment]
Hi and thank you for your answer.
When i download there is no 0.16.3 version. Only 0.16
Can you provide me a link with the 0.16.3 version to download?

I tried the 0.16 version anyway ,the way you told me but it is not opening the chrome browser. Should i copy the chromedriver.exe somewhere? Or what am i doing wrong?

Thank you in advance.

Regards.

**Comment by r00tmebaby** [comment]
Hi, 
  I have recently uploaded the latest python version 0.16.4, but be aware that some people have different LinkedIn layout and the program can not find the course videos. It needs an adjustment, unfortunately I have the standard layout and can not reproduce the error to be able to fix it.

The problem is well discussed here, should you want to read it or post another report in regards to this issue.
 https://github.com/r00tmebaby/LinkedIn-Downloader/issues/39 






 >-------- Оригинално писмо --------

 >От: theobserver notifications@github.com

 >Относно: Re: [r00tmebaby/LinkedIn-Downloader] Could not locate element
 exception (#37)

 >До: r00tmebaby/LinkedIn-Downloader  

 >Изпратено на: 04.03.2020 08:25



 
 
  
Hi and thank you for your answer.
 When i download there is no 0.16.3 version. Only 0.16
 Can you provide me a link with the 0.16.3 version to download?  
  
I tried the 0.16 version anyway ,the way you told me but it is not opening the chrome browser. Should i copy the chromedriver.exe somewhere? Or what am i doing wrong?  
  
Thank you in advance.  
  
Regards.
