### ISSUE TITLE
Download Video - IndexError: list index out of range

### ISSUE THREAD

**Issue by fanta2go** [r00tmebaby/LinkedIn-Downloader#39]
Hello together,
the excersice tasks will download correctly but when i want to download a video, i get this error message:

[*] Downloadig excersise file : uebungsdateien_schlagfertigkeit.zip: 81.9kB [00:00, 558kB/s]                            
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedInDL.py", line 538, in downloader
IndexError: list index out of range

**Comment by r00tmebaby** [comment]
Hello @fanta2go,

Please try the last version 0.16.3.

**Comment by fanta2go** [comment]
Hello r00tmebaby,

Thx for your support, videos work now 👍.

I have an bug with the new version 0.16.3, it is not possible to activate "Exercise Files" and so i cant download them.

Do you have paypal?
I want to pay you a coffe 👍!

Sincerely Michael

**Comment by r00tmebaby** [comment]
Hi @fanta2go, 

Nah, you are not obligated to donate mate, but if you really wish you can use the button "Sponsor" at the top to buy me a coffee. You will be the first actually.

<img src='https://i.gyazo.com/bbcbcf795eff485a674b039632338fc0.png'>

**Comment by fanta2go** [comment]
Okay, thank you - i will wait for an update :-).

**Comment by r00tmebaby** [comment]
@fanta2go, can you tell me what course are you trying to download so I can reproduce the error.

I tried a couple and exercise downloading seemed to work correctly.

**Comment by fanta2go** [comment]
If i start your downloader and go to download and check the box "Exercise Files", the box will unchecked automatically.

Not possible to check the box.

**Comment by r00tmebaby** [comment]
Executable version 0.16.4 is up.

**Comment by fanta2go** [comment]
Have the newest version (0.16.4)...

Now there is no login button:
![1](https://user-images.githubusercontent.com/61649056/75637601-d9749e80-5c27-11ea-80bb-39e988a3d932.png)

If i want to check "Exercise Files":
[Check_ExerciseFiles_Video.zip](https://github.com/r00tmebaby/LinkedIn-Downloader/files/4272865/Check_ExerciseFiles_Video.zip)

**Comment by r00tmebaby** [comment]
@fanta2go 

Can you download it again as I have removed the exercise and subtitles checkbox completely as they are now always on? Multi-course downloading is working and the login is removed in version from version 1.6.4 as it was not working for organisations and some other occasions. Manual login is required.

**Comment by fanta2go** [comment]
Hi r00tmebaby,

get this message again, if i click on "Start".


DevTools listening on ws://127.0.0.1:50625/devtools/browser/5f9113e6-6f1a-4f68-897b-9c313b704e32
###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    01/03/2020            #
#     @version: GUI 0.16.4                    #
##############################################

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "Loader.py", line 386, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name.course-body__info-tab-name-content.ember-view"}
  (Session info: chrome=80.0.3987.122)

**Comment by fanta2go** [comment]
Is the problem eventuelly the layout?

![Unbenannt](https://user-images.githubusercontent.com/61649056/75717428-64f63a00-5cd1-11ea-8804-e60dd75826ea.PNG)

**Comment by fastmarketo** [comment]
Is 7 course/day restriction still there?

**Comment by fanta2go** [comment]
Dont have an restriction, but i have anotherlayout...

**Comment by r00tmebaby** [comment]
Hm, I tried the course that you have and seems to work with me. Anyways the video below can help you as a reference with the login should you have problems with that too.

<video src='https://www.youtube.com/watch?v=wSzYSg4wI2M'></video>

**Comment by fanta2go** [comment]
Hello r00tmebaby,
i have changed nothing in my account - linkedin changed my layout automatically.
Yesterday i had the same layout like you and i could download 1-2 courses.
Since today i have the new layout.
I think the only way is to adjust the new layout.
I will try your ideas.

**Comment by r00tmebaby** [comment]
Thanks, man, that's the only way. I have to push Linkedin to set me your layout. It should be related to something, account, IP, browser agent or OS variations... can not be something else.

**Comment by fanta2go** [comment]
Hello,

today i used the account from a workmate, he got the "classic" design.
So i can sure say, the language doesn't matter.

If i login into my own account at work, i have the same new design.

Im not sure when the design change, i think this happen if you watch a lot of different courses.

Can i send you the the layout?

**Comment by r00tmebaby** [comment]
So that probably means the new design is bind to the account itself not related to anything else. 

I left the program last night and had 25+ courses successfully downloaded, though the layout is still the same.

**Comment by r00tmebaby** [comment]
If the account with this new layout is not important to you, you could send me the login credentials so I can do the fix.

**Comment by fanta2go** [comment]
Ok, thank you.  
Sent you an E-Mail to r00tme@abv.bg

**Comment by r00tmebaby** [comment]
Can you try again, please

**Comment by fanta2go** [comment]
Sent you an E-Mail, hope it is possible to solve this problem.

**Comment by theobserver** [comment]
Hi all,
this is very strange.

With the 16.4 executable version I had to stop and start a couple of times to make it work as the youtube video of rootmebaby shows.
The program managed to download : https://www.linkedin.com/learning/seo-keyword-strategy-2

But i cannot download afterwards this : https://www.linkedin.com/learning/learning-excel-2019/build-your-foundation-in-excel

Regards.

**Comment by r00tmebaby** [comment]
Hello all,

I have a good and a piece of bad news for you. The good news is that I have created a new account and finally got the layout that you have. That's good because now I can work on it to fix the issue.

The bad news is that it will take a while because looking onto the layout change it seems that they made drop-down for a reason to block or at least make it harder for reverse-engineering. That's not a problem because I am going to use a radical solution to the problem won't deal with the design but this will take a while because have to re-forge the whole logic.

Stay tuned for updates.
Regards.

**Comment by fanta2go** [comment]
Ok thank you, will wait for Updates :-).

**Comment by theobserver** [comment]
Thank you mate.

**Comment by r00tmebaby** [comment]
Ýou can try out the new version, it's python only for now.

https://github.com/r00tmebaby/LinkedIn-Downloader/tree/master/Python%20Source%20Code/Version%200.16.5

**Comment by theobserver** [comment]
Hi again,
 ok i tried it , and this is what happened: [here](http://35.208.168.38/~topgreek/!Various/python16.5.mp4)

**Comment by fanta2go** [comment]
I could download the first Video of a complete course and then i got a crash:

[*] Working on course https://www.linkedin.com/learning/sql-grundkurs-2-aufgaben-und-losungen/willkommen-zu-sql-grundkurs-2-aufgaben-und-losungen
[*] 0000_Willkommen Zu Sql Grundkurs 2 Aufgaben Und Losungen: 6.50MB [00:00, 8.41MB/s]
[*] 0000_Willkommen Zu Sql Grundkurs 2 Aufgaben Und Losungen.srt: 8.19kB [00:00, 10.5kB/s]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Michael\Desktop\LinkedIn-Downloader-master\Python Source Code\Version 0.16.5\Loader.py", line 461, in new_layout
    driver.find_element_by_class_name("vjs-next-button").click()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=80.0.3987.132)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Michael\Desktop\LinkedIn-Downloader-master\Python Source Code\Version 0.16.5\Loader.py", line 615, in downloader
    new_layout(driver, items_for_download)
  File "C:\Users\Michael\Desktop\LinkedIn-Downloader-master\Python Source Code\Version 0.16.5\Loader.py", line 491, in new_layout
    if driver.find_element_by_css_selector(".vjs-control.vjs-button.vjs-next-button.vjs-disabled").is_displayed():
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".vjs-control.vjs-button.vjs-next-button.vjs-disabled"}
  (Session info: chrome=80.0.3987.132)

**Comment by r00tmebaby** [comment]
Hi,

I have added a small fix, can you re-download the last version and test it, please.

**Comment by theobserver** [comment]
Hi,
the exercise files are being downloaded ok.
The problems i see are:
1. The download speed is rather slow. It starts ok but up to now i am writing this has fallen to 1.72 Kb/sec which is rather slow. (I am not downloading anything else or using my internet)
2. The program is not downloading the chapters one by one. It downloads the chapter it will see playing that time in chrome.

If you find useful to see a video of what is going on please say so, so i will upload one.

Regards.
