### ISSUE TITLE
NoSuchElementException: Message: no such element: Unable to locate element: 

### ISSUE THREAD

**Issue by gpowa** [r00tmebaby/LinkedIn-Downloader#40]
Hello @r00tmebaby ,

it give me the folling error. What can i do ? I try to change geolocation
over developer Tools and Sensors (Google Maps worked), but no download
possible. It happend in Version 16.4 too.

Here is the log:

> DevTools listening on ws://127.0.0.1:14015/devtools/browser/baa198e7-6441-4a6d-a0c3-d8dee1bcb665
###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    07/02/2020            #
#     @version: GUI 0.16.2                    #
##############################################

[*] Trying to login on LinkedInException in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedInDL.py", line 453, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name-content"}
  (Session info: chrome=80.0.3987.122)

**Comment by gpowa** [comment]
can i send you account to see if this is geolocation or language problems?

**Comment by r00tmebaby** [comment]
Yes, please. That would be the best and fastest option. We can find a solution to this odd problem with the layout. Send it to r00tme@abv.bg or ludzspy@gmail.com

**Comment by gpowa** [comment]
Hello, I have make changes to solve the verification problem

**Comment by ghost** [comment]
...and what did you change to solve this problem?

**Comment by gpowa** [comment]
Hello @r00tmebaby 

Problem still perisist, i send you cred for loging and manage your verfication.

DevTools listening on ws://127.0.0.1:20145/devtools/browser/73e27ea6-d7a0-4dc9-9079-4934a021faf1
###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    01/03/2020            #
#     @version: GUI 0.16.4                    #
##############################################

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "Loader.py", line 387, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name.course-body__info-tab-name-content.ember-view"}
  (Session info: chrome=80.0.3987.132)

**Comment by gpowa** [comment]
@r00tmebaby 

Ok i tested with 16.5 and worked well.
Thank You
