### ISSUE TITLE
Help - Error

### ISSUE THREAD

**Issue by HeIp** [r00tmebaby/LinkedIn-Downloader#46]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "Loader.py", line 353, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by r00tmebaby** [comment]
Hi, 

Obviously the program can not find Chrome browser installed. You need the Chrome browser installed and Chrome driver placed in the program directory.

**Comment by HeIp** [comment]
When I click stop it closes the browser tho? - All versions

**Comment by r00tmebaby** [comment]
Well, if you use the versions that use selenium driver (chrome driver) they close all opened chrome browsers/windows. You can use Lynda downloader to avoid that behaviour.
