### ISSUE TITLE
CSS Layout updated

### ISSUE THREAD

**Issue by h4mp3l** [r00tmebaby/LinkedIn-Downloader#50]
It seems like they updated the site layout again, so the css selector does not work properly anymore:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "Loader.py", line 456, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name.course-body__info-tab-name-content.ember-view"}
  (Session info: chrome=80.0.3987.149)

**Comment by percysl** [comment]
Hi, ye same error:  0.16.4 version

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "Loader.py", line 383, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=80.0.3987.149)

Please please help us, thank you.

**Comment by NathBabs** [comment]
> 
> 
> It seems like they updated the site layout again, so the css selector does not work properly anymore:
> 
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "threading.py", line 932, in _bootstrap_inner
> File "threading.py", line 870, in run
> File "Loader.py", line 456, in downloader
> File "site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
> File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
> File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".course-body__info-tab-name.course-body__info-tab-name-content.ember-view"}
> (Session info: chrome=80.0.3987.149)

Any fix yet? i am also getting this error
Please could the cookies be updated
