### ISSUE TITLE
Unable to start Download - getting exceptions

### ISSUE THREAD

**Issue by ghost** [r00tmebaby/LinkedIn-Downloader#64]
hi I was very thrilled to find this but unfortunately it is not working.

First it gave an error for Chromedriver.exe as my Chrome browser version is 83 and the driver which was there did not support it,I replaced the driver but later it gave an exception

Please find the stacktrace below

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 369, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 530, in find_element_by_tag_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"video"}
  (Session info: chrome=83.0.4103.61)

Can you please look into this,thanks

**Comment by ghost** [comment]
now I am getting this error
###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    09/03/2020            #
#     @version: GUI 0.16.5 v2                   #
##############################################

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 375, in downloader
IndexError: list index out of range
