### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by pranavshirgavakar** [r00tmebaby/LinkedIn-Downloader#70]
DevTools listening on ws://127.0.0.1:49693/devtools/browser/b2c4ae59-d7a4-4479-991b-af48f9f907bd
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedInDL.py", line 397, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 80

I am getting this error. What can I do?

**Comment by deephere** [comment]
I am also getting the same error. Chrome is opening but is crashing immediately. but the downloader had worked for me earlier... dont know why am I getting this error now. Someone please help

DevTools listening on ws://127.0.0.1:51919/devtools/browser/a458d483-1ca8-402b-b1ff-d26ecf42afb1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 340, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in _init_
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in _init_
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 80

**Comment by zayidu** [comment]
I am getting the same error above error, , Can someone help with this, please? Thanks in anticipation.

**Comment by zayidu** [comment]
I fixed it by downloading the latest or required chromedriver matching the installed chrome version.

Check your Chrome versions and download the matching chromedriver version from here: https://chromedriver.chromium.org/downloads 
and then replace the file in the folder.

Mine was 83! It works.

However, I get another issue here, Once the download starts after the first video is downloaded, that is it, it isn't downloading any further videos... Has anyone facing the same issue, if you guys fixed post the solutions below. Appreciate it. 
Thanks.

**Comment by KoichaDev** [comment]
@zayidu Can you please share where you pasted the chrome drive version inside of the LinkedIn DL folder?

**Comment by shadowdragon007** [comment]
yes, i am also facing the same issue. its only downloading the first video of chapter.
