### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shadowdragon007** [r00tmebaby/LinkedIn-Downloader#71]
crhrome driver loads and crashes immediately.

DevTools listening on ws://127.0.0.1:52253/devtools/browser/670ca79a-00fb-4325-984b-912151a3bed8
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 340, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85

this is for the latest version

**Comment by shadowdragon007** [comment]
DevTools listening on ws://127.0.0.1:53244/devtools/browser/70d93436-55aa-4a2b-bbaa-d2c9394e0404
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 340, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85

ERROR: The process "chrome.exe" not found.
ERROR: The process "chromedriver.exe" not found.
ERROR: The process "loader.exe" not found.

i tried this on version 16.2 to 16.5 v2

**Comment by shadowdragon007** [comment]
okay, i found the solution. use the same version of chrome driver as ur chrome browser. its working now.
