### ISSUE TITLE
error and not downloading the course entirely

### ISSUE THREAD

**Issue by shadowdragon007** [r00tmebaby/LinkedIn-Downloader#72]
[*] : Lecture(s) : (1 of 2)
[*] : Downloading (001 Knowing what to say)
[*] : Lecture : '001 Knowing what to say' (already downloaded).

[*] : Downloading chapter : (11 of 7)
[+] : Chapter (11 Say It Like You Mean It)
[*] : Found (4) lectures ...

[*] : Downloading chapter : (12 of 7)
[+] : Chapter (12 Look Like You Mean It)
[*] : Found (4) lectures ...

[*] : Downloading chapter : (13 of 7)
[+] : Chapter (13 Confronting Anxiety)
[*] : Found (3) lectures ...

[*] : Downloading chapter : (14 of 7)
[+] : Chapter (14 Conclusion)
[*] : Found (4) lectures ...

only downloading the first video of specific chapter
[4688:14672:0728/220625.738:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/decrypting_video_decoder.cc\",\"line\":53}],\"status_code\":264,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"DecryptingVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[4688:14672:0728/220653.426:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/vpx_video_decoder.cc\",\"line\":135}],\"status_code\":265,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"VpxVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[4688:14672:0728/220653.433:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{\"codec\":\"h264\"},\"stack\":[{\"file\":\"../../media/filters/dav1d_video_decoder.cc\",\"line\":165}],\"status_code\":260,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"Dav1dVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}

**Comment by buddj** [comment]
I'm experiencing the same issue 

DevTools listening on ws://127.0.0.1:54190/devtools/browser/c897e3af-6217-489a-b109-0081e55673e7
###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    09/03/2020            #
#     @version: GUI 0.16.5 v2                   #
##############################################

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 369, in downloader
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 530, in find_element_by_tag_name
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"video"}
  (Session info: chrome=84.0.4147.105)

[7512:7284:0806/181754.306:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/decrypting_video_decoder.cc\",\"line\":53}],\"status_code\":264,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"DecryptingVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/181754.307:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/vpx_video_decoder.cc\",\"line\":135}],\"status_code\":265,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"VpxVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/181754.309:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{\"codec\":\"h264\"},\"stack\":[{\"file\":\"../../media/filters/dav1d_video_decoder.cc\",\"line\":165}],\"status_code\":260,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"Dav1dVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/181847.149:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/decrypting_video_decoder.cc\",\"line\":53}],\"status_code\":264,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"DecryptingVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/181847.149:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/vpx_video_decoder.cc\",\"line\":135}],\"status_code\":265,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"VpxVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/181847.151:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{\"codec\":\"h264\"},\"stack\":[{\"file\":\"../../media/filters/dav1d_video_decoder.cc\",\"line\":165}],\"status_code\":260,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"Dav1dVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/182037.371:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/decrypting_video_decoder.cc\",\"line\":53}],\"status_code\":264,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"DecryptingVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/182037.373:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{},\"stack\":[{\"file\":\"../../media/filters/vpx_video_decoder.cc\",\"line\":135}],\"status_code\":265,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"VpxVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
[7512:7284:0806/182037.374:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"{\"causes\":[{\"causes\":[],\"data\":{\"codec\":\"h264\"},\"stack\":[{\"file\":\"../../media/filters/dav1d_video_decoder.cc\",\"line\":165}],\"status_code\":260,\"status_message\":\"\"}],\"data\":{\"Decoder name\":\"Dav1dVideoDecoder\"},\"stack\":[{\"file\":\"../../media/filters/decoder_selector.cc\",\"line\":172}],\"status_code\":265,\"status_message\":\"\"}"}
SUCCESS: The process "chrome.exe" with PID 8180 has been terminated.
SUCCESS: The process "chrome.exe" with PID 10248 has been terminated.
SUCCESS: The process "chrome.exe" with PID 5096 has been terminated.
SUCCESS: The process "chrome.exe" with PID 11960 has been terminated.
SUCCESS: The process "chrome.exe" with PID 9128 has been terminated.
SUCCESS: The process "chrome.exe" with PID 7744 has been terminated.
SUCCESS: The process "chrome.exe" with PID 11712 has been terminated.
SUCCESS: The process "chrome.exe" with PID 8780 has been terminated.
SUCCESS: The process "chrome.exe" with PID 6092 has been terminated.
SUCCESS: The process "chrome.exe" with PID 9224 has been terminated.
SUCCESS: The process "chrome.exe" with PID 10968 has been terminated.
SUCCESS: The process "chrome.exe" with PID 7512 has been terminated.
SUCCESS: The process "chrome.exe" with PID 9188 has been terminated.
SUCCESS: The process "chrome.exe" with PID 11984 has been terminated.
SUCCESS: The process "chrome.exe" with PID 1856 has been terminated.
SUCCESS: The process "chrome.exe" with PID 9740 has been terminated.
SUCCESS: The process "chromedriver.exe" with PID 4816 has been terminated.
ERROR: The process "loader.exe" not found.

**Comment by shadowdragon007** [comment]
hi, for ur problem, try using the chrome driver, that is same version as ur chrome browser

**Comment by buddj** [comment]
Hi,
Thanks - changed to chromedriver 84 & now the course structure is downloaded & folders created but not all the videos are downloaded. Video 1 will download then 7 then 9 but nothing inbetween.......

**Comment by shadowdragon007** [comment]
try it multiple times. it may be a software issue or with ur internet speed. keep downloading the course, eventually entire course will be downloaded. also, try updating the python to the latest version

**Comment by buddj** [comment]
I'm using Python 3.8.5
Broadband details --
      Ping - 17 ms
      Download speed - 14.62 Mb/s
      Upload speed - 0.82 Mb/s
Have tried the process 20 times & across multiple courses & on multiple OS's. Once the first run is complete no additional videos are downloaded.

Any other suggestions shadowdragon007 ??

**Comment by JoeDDev** [comment]
I have the same problema, how can I download all the videos? It only download 1 or 2 videos from a course... :(
please help @r00tmebaby

**Comment by r00tmebaby** [comment]
Hi there,

Please state which version of the program you are using and also which course you are trying to download. You need to log in to be able to download any courses, otherways the program download only those chapters which are free and accessible without an account.

Reagrds,

**Comment by shadowdragon007** [comment]
DevTools listening on ws://127.0.0.1:54811/devtools/browser/08f70802-4322-4539-a7d2-5af8b4549220
[24828:9368:0616/105432.856:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[12232:5004:0616/105433.842:ERROR:device_event_log_impl.cc(214)] [10:54:33.842] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[12232:5004:0616/105433.854:ERROR:device_event_log_impl.cc(214)] [10:54:33.844] USB: usb_service_win.cc:389 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
###############################################
#     LinkedIn Learning Download              #
#     @author r00tme    09/03/2020            #
#     @version: GUI 0.16.5 v2                   #
##############################################

[12232:5004:0616/105433.855:ERROR:device_event_log_impl.cc(214)] [10:54:33.855] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[12232:5004:0616/105433.857:ERROR:device_event_log_impl.cc(214)] [10:54:33.857] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[12232:5004:0616/105433.949:ERROR:device_event_log_impl.cc(214)] [10:54:33.949] Bluetooth: bluetooth_adapter_winrt.cc:1203 Getting Radio failed. Chrome will be unable to change the power state by itself.
[12232:5004:0616/105433.999:ERROR:device_event_log_impl.cc(214)] [10:54:33.999] Bluetooth: bluetooth_adapter_winrt.cc:1296 OnPoweredRadiosEnumerated(), Number of Powered Radios: 0
[*] Found Lynda Course ID learning-original-video-vbr-540
--------------Ready to Download------------
[*] Working on course https://www.linkedin.com/learning/creating-a-culture-of-strategy-execution
[*] : Trying to login using cookies ...
[+] : Logged in successfully.
Traceback (most recent call last):on ..
  File "lynda-dl.py", line 389, in <module>
  File "lynda-dl.py", line 349, in main
  File "lynda-dl.py", line 156, in course_download
  File "lynda\_lynda.py", line 38, in course
  File "lynda\_internal.py", line 43, in __init__
  File "lynda\_shared.py", line 65, in __init__
  File "lynda\_internal.py", line 55, in _fetch_course
  File "lynda\_extract.py", line 243, in _real_extract
  File "lynda\_extract.py", line 74, in _extract_course_info
AttributeError: 'NoneType' object has no attribute 'group'
[18264] Failed to execute script lynda-dl
