### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Saku241** [r00tmebaby/LinkedIn-Downloader#82]
I got this when clicking on start (0.16.5 v2 windows executable)

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 340, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
```

**Comment by smdgenesis** [comment]
same

**Comment by m4caque** [comment]
Downloading chromedriver from https://chromedriver.storage.googleapis.com/97.0.4692.71/chromedriver_win32.zip and replacing the chromedriver.exe file in the last version fixes this issue, but once logged in another issue still prevents download
